const SEPOLIA_RPC_HTPPS = process.env.NEXT_PUBLIC_SEPOLIA_RPC_HTPPS ? process.env.NEXT_PUBLIC_SEPOLIA_RPC_HTPPS : "none"
const SEPOLIA_RPC_WEBSOCKET = process.env.NEXT_PUBLIC_SEPOLIA_RPC_WEBSOCKET ? process.env.NEXT_PUBLIC_SEPOLIA_RPC_WEBSOCKET : "none"

